print('hola mundo')
print('hola','mundo')
print('hola','mundo',sep='\n')
print('home', 'user', 'documents', sep='/')
print('', 'home', 'user', 'documents', sep='/')
print('node', 'child', 'child', sep=' -> ')
print('Checking file integrity...', end='')
print('ok')
print()
print('The first sentence', end='. ')
print('The second sentence', end='. ')
print('The last sentence.')
print('hello', end='\n')
print('ok')